### ISSUE TITLE
Inheritation

### ISSUE THREAD

**Issue by Gholamalih** [SingletonSean/reservoom#1]
https://github.com/SingletonSean/reservoom/blob/0a97856e30008bfd4363a2cde8ed8b4347a01f8b/src/Reservoom/ViewModels/ReservationViewModel.cs#L10

Why do we need to inherit from ViewModelBase for this class?

**Comment by Farka739** [comment]
Check the 3 tutorial lesson on his channel. This is the name of the video. View Models - WPF MVVM TUTORIAL #3

> https://github.com/SingletonSean/reservoom/blob/0a97856e30008bfd4363a2cde8ed8b4347a01f8b/src/Reservoom/ViewModels/ReservationViewModel.cs#L10
> 
> Why do we need to inherit from ViewModelBase for this class?

**Comment by Gholamalih** [comment]
> Check the 3 tutorial lesson on his channel. This is the name of the video. View Models - WPF MVVM TUTORIAL #3
> 
> > https://github.com/SingletonSean/reservoom/blob/0a97856e30008bfd4363a2cde8ed8b4347a01f8b/src/Reservoom/ViewModels/ReservationViewModel.cs#L10
> > 
> > Why do we need to inherit from ViewModelBase for this class
